development: &defaults
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://localhost:5432/ask_question_development') %>

test:
  <<: *defaults
  url: <%= ENV.fetch('DATABASE_URL', "postgres://localhost:5432/ask_question_test#{ENV['TEST_ENV_NUMBER']}") %>

staging:
  <<: *defaults

production:
  <<: *defaults
